- name: Deploy Edx Marketing
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - apache
    - role: edx_mktg
      nginx_default_sites:
        - edx_mktg
